repository:
  name: closecircuit
  description: "🚗📷📱 Open source software & hardware for a backup camera/baby monitor/whatever offline CCTV system."
  topics: android, automotive, backup-camera, baby-monitor, cctv, camera, video, offline, hardware, software, open-source
